# Generated by Django 4.2 on 2023-08-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_project',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
