# Generated by Django 4.2 on 2023-08-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_project_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog_project',
            name='url',
        ),
        migrations.AlterField(
            model_name='blog_project',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blog_project',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
